import { API_CONFIG } from '@repo/apis'

export const ENDPOINTS = {
  ROBOT: {
    AUTH: `${API_CONFIG.PREFIX_AUTH}`,
    DEVICES: `${API_CONFIG.PREFIX_ROBOT}/devices`,
    FILES: `${API_CONFIG.PREFIX_ROBOT}/files`,
    GROUPS: `${API_CONFIG.PREFIX_ROBOT}/groups`,
    MAPS: `${API_CONFIG.PREFIX_ROBOT}/maps`,
    SITES: `${API_CONFIG.PREFIX_ROBOT}/sites`,
    USERS: `${API_CONFIG.PREFIX_ROBOT}/users`
  },
  AI: {
    EVENT_RECEIVER: `${API_CONFIG.PREFIX_AI_EVENTS}`,
    EVENT_ANALYZER: `${API_CONFIG.PREFIX_AI_ANALYSIS}`,
    CONFIG_MANAGER: `${API_CONFIG.PREFIX_AI_CONFIG}`,
    ACTION_RUNNER: `${API_CONFIG.PREFIX_AI_ACTIONS}`,
    REPORT_MANAGER: `${API_CONFIG.PREFIX_AI_REPORTS}`
  }
}

export const GETSIZE = '100'

